version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Net.Compilers
    versions:
    - 3.8.0
    - 3.9.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: NCrunch.Framework
    versions:
    - 4.5.0
    - 4.7.0.4
  - dependency-name: Machine.Specifications
    versions:
    - 1.0.0
  - dependency-name: Machine.Specifications.Runner.VisualStudio
    versions:
    - 2.10.1
  - dependency-name: Machine.Specifications.Should
    versions:
    - 1.0.0
